blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/padparadscho/soroban-escrow-database/blob/main/README.md
    about: Comprehensive documentation for the soroban-escrow-database repository.
  - name: X (Twitter)
    url: https://x.com/padparadscho
    about: Follow Padparadscho on X (Twitter) for updates, discussions or just to say hi!
